name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # Используем официальный контейнер, где уже всё установлено
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        run: |
          # Устанавливаем права на директорию
          chown -R root:root .
          
          # Автоматически принимаем лицензии (на всякий случай)
          export BUILDOZER_ACCEPT_SDK_LICENSE=1
          
          # Запускаем сборку
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: marathon-app-apk
          # Buildozer по умолчанию складывает APK в папку bin
          path: bin/*.apk
